config/routes.rb
Postshow::Application.routes.draw do
  resources :posts,:comments

end

app/models/account.rb
class Account < ActiveRecord::Base
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  validates :post_id,:valuate, :presence => true
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comment
  validates :title,:author,:description, :presence => true
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  has_one :post
  def login
    
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @comments = Comment.all
    
    respond_to do |format|
      format.html
      format.json { render json: @comments }
    end
  end
  
  def new
    @comment = Comment.new
    
    respond_to do |format|
      format.html
      format.json { render json: @comemnt }
   
    
    end
  end
  
  def show
    @com = Comment.find(params[:id])
    @comment = Comment.new

    @comment.save
    
    respond_to do |format|
      format.html
      format.json { render json: @comment }
    end
  end
  
  def edit
    @comment = Comment.find(params[:id])
    
  end
  
  def create
    @comment = Comment.new(params[:comment])
    @comment.post_id = params[:post_id]
    @comment.valuate = params[:valuate]
    
    respond_to do |format|
      if @comment.save
        format.html { redirect_to :back, notice: 'Post was successfully created.' }
        format.json { render json: @comment, status: :created, location: @comment }
      else
        format.html { redirect_to :back,notice: "No valuate" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def update
    @comment = Comment.find(params[:comment])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to @comment, notice: "Post was successfully created" }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end
  
  def new
    @post = Post.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end
  
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def show
    @post = Post.find(params[:id])
    @comment = Comment.where("post_id = ?",params[:id])
    @post_id = @post.id

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end
  
  def edit
    @post = Post.find(params[:id])
    
  end
  
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: "Post was successfully created" }
        format.json { head :ok }
      else
        format.html { render action: "show" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>

<table>
	<tr>
		<th>题目</th>
		<th>作者</th>
	</tr>
</table>
<%= f.submit %>
<% end %>

app/views/comments/index.html.erb
<h1>文章列表</h1>

<table align="center">
	<tr>
		<th>题目</th>
		<th>作者</th>
	</tr>
	<%= @comments.each do |comment| %>
	<tr>
		<td><%= h(comment.title) %></td>
		<td><%= h(comment.author) %></td>
		<td><%= link_to "查看",comment %></td>
	</tr>
	<% end %>
</table>

app/views/comments/new.html.erb
<div>
	<h5>你并没有评论</h5>
</div>
<%= link_to "返回",post %>

app/views/comments/show.html.erb
<%= form_for(@comment) do |f| %>

<div align="center">
	<%= h(@com.title) %><br />
	<%= h(@com.author) %><br />
	<%= f.text_area :valuate %>
</div>
<%= f.submit %>
<% end %>
<%= link_to "返回",comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Postshow</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div>
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div>
  	<%= f.text_field :title %><br /><br />
  	<%= f.text_field :author %><br /><br />
  	<%= f.text_area :description %><br /><br />
  	<%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<%= render 'form' %>

app/views/posts/index.html.erb
<h1>Post list</h1>
<table>
	<tr>
		<th>题目</th>
		<th>作者</th>
		<th>上传时间</th>
		<th>最后修改时间</th>
	</tr>
	<% @posts.each do |post| %>
	<tr>
		<td><%= post.title %></td>
		<td><%= post.author %></td>
		<td><%= post.created_at %></td>
		<td><%= post.updated_at %></td>
		<td><%= link_to "阅读",post %></td>
	</tr>
	<% end %>
</table><br />
<%= link_to "发表文章",new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>


<%= render 'form' %>

app/views/posts/show.html.erb
<div align="center">
	<h1><%= @post.title %></h1>	
</div>
<div align="center">
	<h2><%= @post.author %></h2>
</div>
<div align="center">
	<%= @post.description %><br />
	<%= label_tag "评论:" %><br />
<%= form_tag({ :controller => "comments",:action => "create"},:method =>"post") do  %>

	<% @comment.each do |comment| %>
	
	<%= comment.valuate %>&nbsp;<h6><%= comment.created_at %></h6><br />
	
	<% end %>
</div>
<div align="center">
	<%= hidden_field_tag "post_id",@post_id %><br />
<%= text_area_tag "valuate" %><br />
<%= submit_tag "评论" %>
</div>
<% end %>
<div align="center">
	<% link_to "返回", posts_path %>
</div>